Made some adjustments to the script to ensure the [] character is not included when getting the ami name

diff --git a/.github/workflows/image-ami-builds.yaml b/.github/workflows/image-ami-builds.yaml
--- a/.github/workflows/image-ami-builds.yaml
+++ b/.github/workflows/image-ami-builds.yaml
@@ -70,7 +70,7 @@ jobs:
              AWS_REGION: ${{ env.AWS_REGION }}
            run: |
              if [ -f "./output/packer-manifest.json" ]; then
-               AMI_ID=$(jq -r '.builds[-1].artifact_id' < ./output/packer-manifest.json | cut -d':' -f2 | cut -d',' -f1 | tr -d '[]')
+               AMI_ID=$(jq -r '.builds[-1].artifact_id' < ./output/packer-manifest.json | cut -d':' -f2 | cut -d',' -f1 | tr -d '[]' | xargs)
                aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\": [{\"Group\":\"all\"}]}"
                echo "AMI $AMI_ID is now public."
              else
@@ -78,12 +78,12 @@ jobs:
                echo "Searching for packer-manifest.json in the current directory..."
                PACKER_MANIFEST_PATH=$(find . -name "packer-manifest.json" | head -n 1)
                if [ -n "$PACKER_MANIFEST_PATH" ]; then
-                echo "Found packer-manifest.json at $PACKER_MANIFEST_PATH"
-                AMI_ID=$(jq -r '.builds[-1].artifact_id' < "$PACKER_MANIFEST_PATH" | cut -d':' -f2 | cut -d',' -f1 | tr -d '[]')
-                aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\": [{\"Group\":\"all\"}]}"
-                echo "AMI $AMI_ID is now public."
+               echo "Found packer-manifest.json at $PACKER_MANIFEST_PATH"
+               AMI_ID=$(jq -r '.builds[-1].artifact_id' < "$PACKER_MANIFEST_PATH" | cut -d':' -f2 | cut -d',' -f1 | tr -d '[]' | xargs)
+               aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\": [{\"Group\":\"all\"}]}"
+               echo "AMI $AMI_ID is now public."
                else
-                echo "Error: packer-manifest.json file could not be found."
-                exit 1
+               echo "Error: packer-manifest.json file could not be found."
+               exit 1
                fi
              fi
