Updated script so it updates each ami ID it creates and makes each image public

diff --git a/.github/workflows/image-ami-builds.yaml b/.github/workflows/image-ami-builds.yaml
--- a/.github/workflows/image-ami-builds.yaml
+++ b/.github/workflows/image-ami-builds.yaml
@@ -30,6 +30,24 @@ jobs:
          ACCOUNT_ID: "261908217831"
          ROLE: "image-builder-runner"
          AWS_OUTPUT: "json"
+      strategy:
+         matrix:
+            region:
+               - us-east-1
+               - us-east-2
+               - us-west-1
+               - us-west-2
+               - ap-south-1
+               - ap-northeast-1
+               - ap-northeast-2
+               - ap-southeast-1
+               - ap-southeast-2
+               - ca-central-1
+               - eu-central-1
+               - eu-west-1
+               - eu-west-2
+               - eu-west-3
+               - sa-east-1
 
       steps:
          - name: Checkout repository
@@ -70,20 +88,35 @@ jobs:
              AWS_REGION: ${{ env.AWS_REGION }}
            run: |
              if [ -f "./output/packer-manifest.json" ]; then
-               AMI_ID=$(jq -r '.builds[-1].artifact_id' < ./output/packer-manifest.json | cut -d':' -f2 | cut -d',' -f1 | tr -d '[]' | xargs)
-               aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\": [{\"Group\":\"all\"}]}"
-               echo "AMI $AMI_ID is now public."
+               echo "Found packer-manifest.json in the expected location."
+               for REGION in ${{ matrix.region }}; do
+                AMI_ID=$(jq -r --arg REGION "$REGION" '.builds[] | select(.region == $REGION) | .artifact_id' < ./output/packer-manifest.json | cut -d':' -f2 | xargs)
+                if [ -n "$AMI_ID" ]; then
+                  echo "Making AMI $AMI_ID in region $REGION public."
+                  aws ec2 modify-image-attribute --region $REGION --image-id $AMI_ID --launch-permission "{\"Add\": [{\"Group\":\"all\"}]}"
+                  echo "AMI $AMI_ID in region $REGION is now public."
+                else
+                  echo "No AMI found for region $REGION in packer-manifest.json."
+                fi
+               done
              else
                echo "Error: packer-manifest.json file not found in the expected location."
                echo "Searching for packer-manifest.json in the current directory..."
                PACKER_MANIFEST_PATH=$(find . -name "packer-manifest.json" | head -n 1)
                if [ -n "$PACKER_MANIFEST_PATH" ]; then
-               echo "Found packer-manifest.json at $PACKER_MANIFEST_PATH"
-               AMI_ID=$(jq -r '.builds[-1].artifact_id' < "$PACKER_MANIFEST_PATH" | cut -d':' -f2 | cut -d',' -f1 | tr -d '[]' | xargs)
-               aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\": [{\"Group\":\"all\"}]}"
-               echo "AMI $AMI_ID is now public."
+                echo "Found packer-manifest.json at $PACKER_MANIFEST_PATH"
+                for REGION in ${{ matrix.region }}; do
+                  AMI_ID=$(jq -r --arg REGION "$REGION" '.builds[] | select(.region == $REGION) | .artifact_id' < "$PACKER_MANIFEST_PATH" | cut -d':' -f2 | xargs)
+                  if [ -n "$AMI_ID" ]; then
+                   echo "Making AMI $AMI_ID in region $REGION public."
+                   aws ec2 modify-image-attribute --region $REGION --image-id $AMI_ID --launch-permission "{\"Add\": [{\"Group\":\"all\"}]}"
+                   echo "AMI $AMI_ID in region $REGION is now public."
+                  else
+                   echo "No AMI found for region $REGION in packer-manifest.json."
+                  fi
+                done
                else
-               echo "Error: packer-manifest.json file could not be found."
-               exit 1
+                echo "Error: packer-manifest.json file could not be found."
+                exit 1
                fi
              fi
